# -*- mode: ruby -*-
# vi: set ft=ruby :

$configuration_script = <<SCRIPT
echo "Installing dependencies for Consul ..."
sudo apt-get update
sudo apt-get install -y unzip curl jq dnsutils
echo "Determining Consul version to install ..."
CHECKPOINT_URL="https://checkpoint-api.hashicorp.com/v1/check"
if [ -z "$CONSUL_DEMO_VERSION" ]; then
CONSUL_DEMO_VERSION=$(curl -s "${CHECKPOINT_URL}"/consul | jq .current_version | tr -d '"')
fi
echo "Fetching Consul version ${CONSUL_DEMO_VERSION} ..."
cd /tmp/
curl -s https://releases.hashicorp.com/consul/${CONSUL_DEMO_VERSION}/consul_${CONSUL_DEMO_VERSION}_linux_amd64.zip -o consul.zip
echo "Installing Consul version ${CONSUL_DEMO_VERSION} ..."
unzip consul.zip
sudo chmod +x consul
sudo mv consul /usr/bin/consul
sudo mkdir /etc/consul.d
sudo chmod a+w /etc/consul.d
SCRIPT

CONSUL_DEMO_VERSION = ENV['CONSUL_DEMO_VERSION']

DEMO_BOX_NAME = ENV['DEMO_BOX_NAME'] || "debian/stretch64"

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = DEMO_BOX_NAME

config.vm.provision "shell",
	inline: $configuration_script,
	env: {'CONSUL_DEMO_VERSION' => CONSUL_DEMO_VERSION}

	config.vm.define "server1" do |server1|
		server1.vm.hostname = "server1"
		server1.vm.network "private_network", ip: "10.1.142.101"
	end

	config.vm.define "server2" do |server2|
		server2.vm.hostname = "server2"
		server2.vm.network "private_network", ip: "10.1.142.102"
	end

	config.vm.define "server3" do |server3|
		server3.vm.hostname = "server3"
		server3.vm.network "private_network", ip: "10.1.142.103"
	end
end